server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3310/calendfi?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: admin
    password: NIcai123456!
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 20MB
  redis:
    host: localhost
    port: 3315
    timeout: 5000ms
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.ach.calendfi
logging:
  level:
    com.ach.calendfi.dao : debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
dappos:
  url: "http://18.222.137.245:9100"