server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://database-1.cs1r4uz5q7lc.us-east-2.rds.amazonaws.com:3306/calendfi?useSSL=false&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: admin
    password: NIcai123456!
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 20MB
  redis:
    host: enc-redis.dtwe0o.ng.0001.use2.cache.amazonaws.com
    port: 6379
    timeout: 5000ms
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  type-aliases-package: com.ach.calendfi
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
dappos:
  url: "https://rpc.dappos.org/"